openapi: "3.0.1"
info:
  version: 0.0.1
  title: Pawnflow API
  description: Pawnflow API
paths:
  /debug:
    get:
      operationId: getDebug
      responses:
        default:
          description: "Default response for GET /debug"
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/debug'

components:
  x-amazon-apigateway-integrations:
    debug:
      type: AWS_PROXY
      httpMethod: GET
      uri: "foo/bar"
      payloadFormatVersion: "2.0"
      connectionType: INTERNET
